# For help completing this file, see the "AppSpec File Reference" in the
#   "AWS CodeDeploy User Guide" at
#   http://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html
version: 0.0

os: linux

files:
  - source: /
    destination: /home/ubuntu/black-forest

hooks:
  BeforeInstall:
    - location: sudo service unicorn_blackforest stop
    - location: script/BeforeInstall.sh
  ApplicationStart:
    - location: sudo service unicorn_blackforest start
      timeout: 180
    - location: sudo service nginx restart
      timeout: 180
